### ISSUE TITLE
License Discussion 

### ISSUE THREAD

**Issue by ansarusc** [UBC-MDS/aRidanalysis#51]

**Comment by nphaterp** [comment]
Our plan is to all visit [choosealicense.com](https://choosealicense.com). From there we will browse and come up with our personal preferences. From there we will have a discussion about the pros/cons of each of the license preferences. 

Finally we will vote on a single license to proceed with.

**Comment by nphaterp** [comment]
Neels Selection:

**1. MIT License**
I selected this license because it is simple it covers the basic usage for our project. Our particular project does not serve the purpose of contributing to any communal project, thus it would be unnecessary to use a license like the Apache License 2.0. The reason I think the MIT License is a good idea is that almost everyone is familiar with it, making it easy for viewers of our package to understand the copyright rules that underlie our project. Moreover, I think the conditions outlined in the MIT License serve the purpose of our project well. Namely, it let's others do what they want with our project while preserving the copyright. 

**2. Boost Software License 1.0** 

This is another license that I would be willing to use. It seems to cover the same things as the MIT license. It does seem that the Boost License goes into a little more detail about what the users are permitted to do. However, this might not be necessary for our project. Furthermore, I had never heard of this license before and this perhaps might be the case for other users. This might slow down the process of others wanting to use our package which is not ideal 

[Reference](https://law.stackexchange.com/questions/91/is-there-any-difference-in-meaning-between-the-boost-and-mit-software-licenses)

**Comment by CraigEnsemble** [comment]
After reviewing the choosealicense.com choices I would vote for either of the 2 licenses:

1. The Unlicense
2. MIT License

The Unlicense: "A license with no conditions whatsoever which dedicates works to the public domain"
* Pros:
    1. Extremely permissible! In the spirit of open source development!
    2. No future maintenance 
    3. As our project is heavily utilizing the works of glmnet and statsmodels, this is probably the most ethical choice.
* Cons:
     1. Our works could theoretically be used for negative purposes without our knowledge
     2. No credit/citation for any of our work
     3. Hard to make license more restrictive in the future

MIT License: "A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code."
* Pros: 
    - Also very permissible and promotes further collaboration.
    - We're already using it; no overhead to change it
    - No upkeep required on our end
* Cons:
    - Doesn't protect code from being taken privately in the future or people rebranding or selling.
    - Hard to make license more restrictive in the future.

**Comment by danielon-5** [comment]
I would also suggest to pick one of the following:

- MIT License
- Boost Software License 1.0

I find both suitable for our package in terms of being permissible and promoting collaboration. Looks like the latter one covers the same as the MIT License plus the license and copyright notice for source and not just only license and copyright notice. However, considering that we already have the MIT one set up, I would choose the MIT License.

**Comment by ansarusc** [comment]
Hello guys, regarding license selection, after reviewing the choices available on the webpage my preferences are:

* MIT License

Given the nature of this package (educational purposes), a permissive and open-ended license seems the most reasonable choice. This MIT License has a reasonable length and it is well-known, meaning that most users will understand its functioning. Moreover, although it invites new users to collaborate and make use of the package, the copyright must be respected.


* ISC License

This license is very similar (almost equivalent) to the MIT license, except that it has better wording and according to the website, it has removed a specific language that was no longer necessary.


Pd: I think most of us agree that keeping MIT License is not a bad idea.

**Comment by nphaterp** [comment]
As a result we have decided to proceed with the MIT License. 

This makes sense for us because the license is pretty flexible and it allows others the opportunities to utilize our package how they see fit. Furthermore, we expect that most people are familiar with the copyright restrictions associated with the MIT license making it even easier for others to quickly start using our package

**Comment by nphaterp** [comment]
As a result of our discussion, we have decided to proceed with the MIT License.

This makes sense for us because the license is pretty flexible and it allows others the opportunities to utilize our package how they see fit. Furthermore, we expect that most people are familiar with the copyright restrictions associated with the MIT license making it even easier for others to quickly start using our package
